spring.application.name=react_subject_back
server.port=8989

# DB 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=react_subject
spring.datasource.password=1234

# MyBatis 설정
mybatis.configuration.map-underscore-to-camel-case=true

mybatis.configuration.jdbc-type-for-null=null
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=kr.co.iei.lecture.model.vo

# Swagger 설정
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

